version: "3.9"
services:
  postgres:
    image: "postgres:14"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "fingames_db"
    expose:
      - 5432

  web:
    build: .
    expose:
      - 8000
    command: >
      bash -c "python manage.py makemigrations --noinput &&
              python manage.py migrate --noinput &&
              gunicorn fingames.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 2"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
      - /etc/letsencrypt/live/moliyaviy.uz/fullchain.pem:/etc/letsencrypt/live/moliyaviy.uz/fullchain.pem
      - /etc/letsencrypt/live/moliyaviy.uz/privkey.pem:/etc/letsencrypt/live/moliyaviy.uz/privkey.pem
      - /etc/letsencrypt/live/moliyaviy.uz/chain.pem:/etc/letsencrypt/live/moliyaviy.uz/chain.pem
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:
