# Generated by Django 5.1 on 2024-08-19 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="text",
            new_name="message",
        ),
    ]
