# Generated by Django 5.1 on 2024-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_rename_text_feedback_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="message",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="projectdescription",
            name="content",
            field=models.TextField(),
        ),
    ]
