# Generated by Django 5.1 on 2024-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_rename_message_feedback_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
    ]
