# Generated by Django 5.1 on 2024-11-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_remove_game_playernum_remove_game_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="content",
            field=models.TextField(default="Write a content of the file"),
            preserve_default=False,
        ),
    ]
