# Generated by Django 5.1 on 2024-11-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_game_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
